site_name: mohaa.brixton.org
site_url: https://mohaa.brixton.org/
hide:
#  - title
#  - navigation
#  - toc
#  - path
theme: 
  name: material
  favicon: 'img/favicon.ico'
markdown_extensions:
  - attr_list
  - toc:
      permalink: '#'
