site_name: mohaa.brixton.org
site_url: https://mohaa.brixton.org/
hide:
#  - title
#  - navigation
#  - toc
#  - path
theme: 
  name: material
  favicon: 'img/favicon.ico'
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.sections
markdown_extensions:
  - attr_list
  - toc:
      permalink: '#'
